### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by bondneverdies** [toptal/disqus_api#12]
As no informations about any license could be found in the project repository, I would like to know which legal terms are applicable to your gem ?

Please see http://www.gnu.org/licenses/license-list.en.html#NoLicense for a summary of the problems that no license would lead to.

**Comment by einzige** [comment]
Thank you very much @bondneverdies , appreciate you are bringing this into our attention!

https://github.com/toptal/disqus_api/commit/a4abaa7cb1afadb78d2a1b4ca6d8c6ea2466654b

**Comment by bondneverdies** [comment]
Thanks about this!
