### ISSUE TITLE
Automatically Detect Rate Limiting

### ISSUE THREAD

**Issue by sfsekaran** [toptal/disqus_api#9]
It would be highly convenient if this gem had the ability to automatically detect rate limiting and be configured to either stop or wait until API calls will be usable again.

**Comment by andrusha** [comment]
Rate limiting is not a responsibility of API-wrapper. There are many ways to solve it and the right one depends on your use-case.

As a simple solution you could use something like https://github.com/kamui/retriable to retry with carefully crafted timeouts until API is available again.
